#! /bin/sh

### BEGIN INIT INFO
# Provides:		iotgateway
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	iotgateway
# Description: 
#  IOT GATEWAY
### END INIT INFO

PIDFILE=/var/run/iotgateway.pid
DAEMON=/usr/local/bin/iotserver
CONFIG_FILE=/etc/iotgateway.conf

#export _SYSTEMCTL_SKIP_REDIRECT=1
. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting daemon:" "iotserver"
	start-stop-daemon --start --quiet --oknodo --background  --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- -c ${CONFIG_FILE}
	log_daemon_msg 0 
	;;
  stop)
	log_daemon_msg "Stopping daemon:" "iotserver"
	start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE}
	rm -f ${PIDFILE}
	;;


  restart)
	log_daemon_msg "Restarting iotserver"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${PIDFILE}
	rm -f ${PIDFILE}
	start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- -c ${CONFIG_FILE}
	;;

  try-restart)
	log_daemon_msg "Restarting iotserver" 
	set +e
	start-stop-daemon --stop --quiet --retry 30 --pidfile ${PIDFILE}
	RET="$?"
	set -e
	case $RET in
	    0)
		# old daemon stopped
		rm -f ${PIDFILE}
		if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- -c ${CONFIG_FILE} ; then
		    log_end_msg 0
		else
		    log_end_msg 1
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)"
		log_end_msg 0
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)"
		log_end_msg 1
		;;
	esac
	;;

  status)
	if init_is_upstart; then
	    exit 1
	fi
	status_of_proc -p ${PIDFILE} ${DAEMON} iotserver && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/iotgateway {start|stop|reload|force-reload|restart|try-restart|status}"
	exit 1
esac

exit 0
